import React, { useEffect, useState } from 'react';
import { Platform, Pressable, useColorScheme, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import { SafeAreaProvider } from 'react-native-safe-area-context';
import { KeyboardProvider } from 'react-native-keyboard-controller';
import { BottomSheetModalProvider } from '@gorhom/bottom-sheet';
import { useFonts, type FontSource } from 'expo-font';
import { Sora_600SemiBold, Sora_700Bold } from '@expo-google-fonts/sora';
import {
  PlusJakartaSans_400Regular, PlusJakartaSans_500Medium, PlusJakartaSans_600SemiBold, PlusJakartaSans_700Bold,
} from '@expo-google-fonts/plus-jakarta-sans';
import { JoinScreen } from './src/screens/JoinScreen';
import { BusChatScreen } from './src/screens/BusChatScreen';
import { LockedScreen } from './src/screens/LockedScreen';
import { loadSession } from './src/services/session';
import { host } from './src/services/host';
import { chatSocket } from './src/services/socket';
import { Txt } from './src/components/Txt';
import type { JoinResponse } from './src/shared/protocol';
import { loadThemePref } from './src/services/prefs';
import { loadSettings } from './src/store/settings';
import { useChat } from './src/store/chatStore';
import { FRAME_MAX, ThemeModeContext, palette, setActiveMode, themed, useThemePref } from './src/theme/tokens';

/**
 * Web (the AbhiBus WebView): Latin subsets of the text fonts and tiny icon-font
 * subsets, generated by scripts/subset-icons.mjs. Icon fonts are registered under
 * the family names the icon sets use, so they're ready before first paint.
 */
const WEB_FONTS: Record<string, FontSource> = Platform.OS === 'web' ? {
  Sora_600SemiBold: require('./assets/fonts/text/Sora_600SemiBold.ttf'),
  Sora_700Bold: require('./assets/fonts/text/Sora_700Bold.ttf'),
  PlusJakartaSans_400Regular: require('./assets/fonts/text/PlusJakartaSans_400Regular.ttf'),
  PlusJakartaSans_500Medium: require('./assets/fonts/text/PlusJakartaSans_500Medium.ttf'),
  PlusJakartaSans_600SemiBold: require('./assets/fonts/text/PlusJakartaSans_600SemiBold.ttf'),
  PlusJakartaSans_700Bold: require('./assets/fonts/text/PlusJakartaSans_700Bold.ttf'),
  ionicons: require('./assets/fonts/Ionicons.subset.ttf'),
  'material-community': require('./assets/fonts/MaterialCommunityIcons.subset.ttf'),
} : {};

/**
 * Root. Two states only: no session -> PNR gate, session -> live chat.
 * A saved, unexpired session resumes straight into the chat (e.g. after the
 * OS killed the app overnight).
 *
 * EMBEDDED (inside the AbhiBus app's WebView, see services/host.ts): there is
 * no PNR gate. The app injects the session; "back" and "chat ended" hand
 * control back to the app with a `close` message.
 */
export default function App() {
  const [fontsLoaded] = useFonts(Platform.OS === 'web' ? WEB_FONTS : {
    Sora_600SemiBold, Sora_700Bold,
    PlusJakartaSans_400Regular, PlusJakartaSans_500Medium, PlusJakartaSans_600SemiBold, PlusJakartaSans_700Bold,
  });
  const session = useChat((s) => s.session);
  const [booting, setBooting] = useState(true);
  // Back from the chat = step out to home, not leave. The session and socket
  // state survive, so the trip stays one tap away ("Exit chat" is in the ⋮ menu).
  const [away, setAway] = useState(false);
  useEffect(() => { setAway(false); }, [session?.token]);

  // Theme: resolve Auto against the OS, set it before any child reads a colour,
  // and remount the tree (key) when it changes so every surface repaints.
  const scheme = useColorScheme();
  const pref = useThemePref((s) => s.pref);
  const mode = pref === 'system' ? (scheme === 'light' ? 'light' : 'dark') : pref;
  setActiveMode(mode);

  useEffect(() => {
    if (host.embedded) {
      // The app owns session and theme; only harmless chat settings (background, text size…) live in this WebView's storage.
      void loadSettings();
      host.ready().then((b) => {
        if (!b) return;
        if (b.theme) useThemePref.getState().setPref(b.theme);
        if (b.session) useChat.getState().setSession(b.session);
      }).finally(() => setBooting(false));
      const offs = [
        host.on('session', (s: JoinResponse) => { if (!s?.token) return; useChat.getState().reset(); useChat.getState().setSession(s); }),
        host.on('theme', (d: { theme?: string }) => { if (d.theme === 'dark' || d.theme === 'light') useThemePref.getState().setPref(d.theme); }),
        host.on('appState', (d: { state?: string }) => { if (d.state === 'active') chatSocket.wake(); }),
      ];
      return () => offs.forEach((off) => off());
    }
    Promise.all([
      loadSettings(),
      loadThemePref().then((p) => useThemePref.getState().setPref(p)),
      loadSession().then((s) => { if (s) useChat.getState().setSession(s); }),
    ]).finally(() => setBooting(false));
  }, []);

  // Tell the app the page is up (it hides its native spinner).
  useEffect(() => { if (host.embedded && fontsLoaded && !booting) host.post('ready', { hasSession: !!useChat.getState().session }); }, [fontsLoaded, booting]);

  if (!fontsLoaded || booting) return <View style={{ flex: 1, backgroundColor: palette.navy }} />;

  return (
    <ThemeModeContext.Provider value={mode}>
    <GestureHandlerRootView style={styles.outer}>
      {/* Phone-width column on tablets / desktop browsers; sheets portal inside it. */}
      <View style={styles.frame}>
      <SafeAreaProvider>
        <KeyboardProvider>
          <BottomSheetModalProvider>
            <StatusBar style={mode === 'dark' ? 'light' : 'dark'} />
            {host.embedded
              ? (session ? <BusChatScreen key={session.token} onBack={() => host.post('close', { reason: 'back' })} />
                : host.boot?.locked ? <LockedScreen lock={host.boot.locked} onBack={() => host.post('close', { reason: 'locked' })} /> : <NoSession />)
              : session && !away ? <BusChatScreen key={session.token} onBack={() => setAway(true)} /> : <JoinScreen onResume={session ? () => setAway(false) : undefined} />}
          </BottomSheetModalProvider>
        </KeyboardProvider>
      </SafeAreaProvider>
      </View>
    </GestureHandlerRootView>
    </ThemeModeContext.Provider>
  );
}

/** Embedded without a session (should not happen; the app always injects one). */
function NoSession() {
  return (
    <View style={styles.empty}>
      <Txt v="title" style={{ textAlign: 'center' }}>Trip chat</Txt>
      <Txt v="body" color={palette.textSecondary} style={{ textAlign: 'center', marginTop: 8 }}>Open trip chat from your booking in the AbhiBus app.</Txt>
      <Pressable onPress={() => host.post('close', { reason: 'no_session' })} style={styles.emptyBtn} accessibilityRole="button">
        <Txt v="bodyStrong">Close</Txt>
      </Pressable>
    </View>
  );
}

const styles = themed(() => ({
  outer: { flex: 1, backgroundColor: palette.outer, alignItems: 'center' },
  frame: {
    flex: 1, width: '100%', maxWidth: FRAME_MAX, backgroundColor: palette.navy, overflow: 'hidden',
    borderLeftWidth: 1, borderRightWidth: 1, borderColor: palette.hairline,
  },
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32 },
  emptyBtn: { marginTop: 20, paddingHorizontal: 24, paddingVertical: 12, borderRadius: 12, backgroundColor: palette.surfaceRaised },
}));
