import createIconSet from '@expo/vector-icons/createIconSet';
import maps from '../../assets/fonts/icons.subset.json';

/**
 * Web build: icon sets from the subset fonts + name tables generated by
 * scripts/subset-icons.mjs (run `npm run icons:subset` after using a new icon;
 * `npm run build:web` fails if one is missing). Same family names as
 * @expo/vector-icons, so App.tsx can preload the fonts before first paint.
 */
export const Ionicons = createIconSet(maps.Ionicons, 'ionicons', require('../../assets/fonts/Ionicons.subset.ttf'));
export const MaterialCommunityIcons = createIconSet(maps.MaterialCommunityIcons, 'material-community', require('../../assets/fonts/MaterialCommunityIcons.subset.ttf'));
