/**
 * API reference served to the Developer portal (GET /console/v1/docs/spec).
 * Keep in sync with http/v1.ts — every path here is implemented.
 * `ex` = example per vertical (or `all`).
 */
type Ex = { req?: unknown; res: unknown };
export interface EndpointSpec { id: string; group: string; method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'WSS'; path: string; title: string; scope?: string; description: string; params: [string, string, string, string][]; ex: Partial<Record<'all' | 'bus' | 'train' | 'flight', Ex>> }

const BUS_STOPS = [
  { code: 'AMRP', name: 'Ameerpet', lat: 17.4375, lng: 78.4483, sched_dep: '2026-10-06T21:30:00+05:30', type: 'boarding' },
  { code: 'GCBW', name: 'Gachibowli', lat: 17.4401, lng: 78.3489, sched_dep: '2026-10-06T22:15:00+05:30', type: 'boarding' },
  { code: 'KRNL', name: 'Kurnool', lat: 15.8281, lng: 78.0373, sched_arr: '2026-10-07T01:30:00+05:30', sched_dep: '2026-10-07T01:50:00+05:30', type: 'rest_stop' },
  { code: 'MJST', name: 'Bengaluru Majestic', lat: 12.9767, lng: 77.5713, sched_arr: '2026-10-07T07:00:00+05:30', type: 'dropping' },
];
const TRAIN_STOPS = [
  { code: 'KCG', name: 'Kacheguda', sched_dep: '2026-10-06T21:00:00+05:30' },
  { code: 'MBNR', name: 'Mahbubnagar', sched_arr: '2026-10-06T22:35:00+05:30', sched_dep: '2026-10-06T22:37:00+05:30' },
  { code: 'KRNT', name: 'Kurnool City', sched_arr: '2026-10-07T00:55:00+05:30' },
  { code: 'YPR', name: 'Yesvantpur', sched_arr: '2026-10-07T07:30:00+05:30' },
];
const FLIGHT_STOPS = [
  { code: 'HYD', name: 'Hyderabad', terminal: 'T1', gate: '12', sched_dep: '2026-10-06T21:50:00+05:30' },
  { code: 'BLR', name: 'Bengaluru', terminal: 'T1', sched_arr: '2026-10-06T23:05:00+05:30' },
];

export const API_SPEC: EndpointSpec[] = [
  { id: 'auth.token', group: 'Authentication', method: 'POST', path: '/v1/oauth/token', title: 'Get a tenant access token',
    description: 'Server-to-server only. Exchange your client ID and secret (Admin → API keys) for a 1-hour access token. Send it as Authorization: Bearer on every call. Never ship it in an app.',
    params: [['grant_type', 'string', 'yes', 'client_credentials'], ['client_id', 'string', 'yes', 'From API keys'], ['client_secret', 'string', 'yes', 'Keep on your server only'], ['scope', 'string', 'no', 'Space-separated subset of the key’s scopes']],
    ex: { all: { req: { grant_type: 'client_credentials', client_id: 'tnt_abhibus_live', client_secret: 'trs_••••••••', scope: 'rooms:write members:write announcements:write' }, res: { access_token: 'eyJhbGciOi…', token_type: 'Bearer', expires_in: 3600, tenant: 'abhibus', scope: 'rooms:write members:write announcements:write' } } } },

  { id: 'rooms.upsert', group: 'Rooms', method: 'PUT', path: '/v1/rooms/by-key/{trip_key}', title: 'Create or get a room for a trip', scope: 'rooms:write',
    description: 'Idempotent: the first call creates the room, later calls return it (and refresh schedule/stops). trip_key is yours and must be unique per trip. Bus: one room per service per date. Train: one train-wide room per run, plus one per coach after charting (scope.parent_trip_key). Flight: one per flight per date, optionally opened only on delay.',
    params: [['trip_key', 'path', 'yes', 'e.g. bus:{operator}:{service}:{date}'], ['vertical', 'enum', 'yes', 'bus | train | flight | custom'], ['title', 'string', 'yes', 'Room header'], ['subtitle', 'string', 'no', 'Operator · bus type, train · coach …'], ['scope', 'object', 'yes', 'Vertical-specific identifiers'], ['schedule', 'object', 'yes', 'departs_at, arrives_at (ISO 8601 with offset)'], ['route.stops[]', 'array', 'yes', 'Ordered stops: code, name, sched_arr/sched_dep; lat/lng for bus; type: boarding | rest_stop | dropping'], ['activation', 'object', 'no', '{mode: always | on_delay, min_delay_min} (flights)'], ['features', 'object', 'no', 'Per-room overrides of tenant features'], ['location_feed', 'enum', 'no', 'none | vts | running_status | flight_status'], ['metadata', 'object', 'no', 'Free-form, returned in webhooks']],
    ex: {
      bus: { req: { vertical: 'bus', title: 'Hyderabad → Bengaluru', subtitle: 'Sunrise Travels · AC Sleeper 2+1', scope: { operator_id: 'op_sunrise', service_id: 'svc-4412', journey_date: '2026-10-06', route: 'HYD-BLR' }, schedule: { departs_at: '2026-10-06T21:30:00+05:30', arrives_at: '2026-10-07T07:00:00+05:30' }, route: { stops: BUS_STOPS }, location_feed: 'vts' }, res: { id: 'room_9f2k1abc', trip_key: 'bus:op_sunrise:svc-4412:2026-10-06', vertical: 'bus', state: 'scheduled', opens_at: '2026-10-06T18:30:00+05:30', read_only_at: '2026-10-07T07:00:00+05:30', member_count: 0, created: true } },
      train: { req: { vertical: 'train', title: 'Kacheguda → Yesvantpur', subtitle: '12999 Deccan Example Express · Coach B2 · 3A', scope: { train_no: '12999', coach: 'B2', class: '3A', parent_trip_key: 'train:12999:2026-10-06' }, schedule: { departs_at: '2026-10-06T21:00:00+05:30', arrives_at: '2026-10-07T07:30:00+05:30' }, route: { stops: TRAIN_STOPS }, location_feed: 'running_status', features: { rest_stop: false, wait_for_me: false } }, res: { id: 'room_t7b20xyz', trip_key: 'train:12999:2026-10-06:B2', vertical: 'train', state: 'scheduled', parent_room_id: 'room_t7a11xyz', created: true } },
      flight: { req: { vertical: 'flight', title: 'Hyderabad → Bengaluru', subtitle: 'Flight XY 512', scope: { carrier: 'XY', flight_no: '512', origin: 'HYD', destination: 'BLR' }, schedule: { departs_at: '2026-10-06T21:50:00+05:30', arrives_at: '2026-10-06T23:05:00+05:30' }, route: { stops: FLIGHT_STOPS }, activation: { mode: 'on_delay', min_delay_min: 45 }, location_feed: 'flight_status', features: { location_crowd: false } }, res: { id: 'room_f3c90abc', trip_key: 'flight:XY512:2026-10-06', vertical: 'flight', state: 'dormant', created: true } },
    } },
  { id: 'rooms.get', group: 'Rooms', method: 'GET', path: '/v1/rooms/{room_id}', title: 'Get a room', scope: 'rooms:read', description: 'The room, its state, timings, counts and best current position.', params: [['room_id', 'path', 'yes', '']],
    ex: { all: { res: { id: 'room_9f2k1abc', vertical: 'bus', state: 'onboard', member_count: 14, delay_min: 25, ops_only: false, location: { near: 'between KPHB and Gachibowli', confidence: 'high', source: '3 travellers on board', contributors: 3 } } } } },
  { id: 'rooms.list', group: 'Rooms', method: 'GET', path: '/v1/rooms', title: 'List rooms', scope: 'rooms:read', description: 'Filter by vertical, state (comma-separated), date (IST) and scope fields. 50 per page.',
    params: [['vertical', 'query', 'no', ''], ['state', 'query', 'no', 'scheduled,dormant,open,onboard,read_only,closed'], ['date', 'query', 'no', 'YYYY-MM-DD'], ['operator_id / train_no / flight_no', 'query', 'no', ''], ['cursor', 'query', 'no', 'next_cursor']],
    ex: { all: { req: 'GET /v1/rooms?vertical=bus&state=open,onboard&operator_id=op_sunrise', res: { data: [{ id: 'room_9f2k1abc', title: 'Hyderabad → Bengaluru', state: 'onboard', member_count: 14 }], next_cursor: null } } } },
  { id: 'rooms.update', group: 'Rooms', method: 'PATCH', path: '/v1/rooms/{room_id}', title: 'Update a room', scope: 'rooms:write', description: 'Change schedule, title, scope (e.g. vehicle_no after allocation), features or meta. Timings shift automatically. Prefer trip events for delays so travellers get an alert.',
    params: [['title / subtitle', 'string', 'no', ''], ['schedule', 'object', 'no', ''], ['scope', 'object', 'no', 'merged'], ['features', 'object', 'no', 'merged']], ex: { all: { req: { scope: { vehicle_no: 'TS09 UB 4412' }, features: { ads: false } }, res: { id: 'room_9f2k1abc', updated: ['scope.vehicle_no', 'features.ads'] } } } },
  { id: 'rooms.close', group: 'Rooms', method: 'POST', path: '/v1/rooms/{room_id}/close', title: 'Close a room', scope: 'rooms:write', description: 'End early (cancelled, merged). Travellers are notified. read_only_for_min: 0 closes immediately.',
    params: [['reason', 'enum', 'yes', 'trip_cancelled | trip_completed | merged | other'], ['read_only_for_min', 'int', 'no', ''], ['message', 'string', 'no', 'Final announcement']], ex: { all: { req: { reason: 'trip_cancelled', read_only_for_min: 0, message: 'This service is cancelled. Your refund is being processed.' }, res: { id: 'room_9f2k1abc', state: 'closed' } } } },

  { id: 'members.add', group: 'Members', method: 'POST', path: '/v1/rooms/{room_id}/members', title: 'Add travellers', scope: 'members:write',
    description: 'One to 500 travellers. Idempotent per external_user_id: one random handle per person per room, even with several seats. Seat, PNR and gender are stored for Ops / gating only and never shown in the room. Send gender only if you want the women-only channel to work.',
    params: [['members[].external_user_id', 'string', 'yes', 'Your user ID'], ['members[].booking_ref', 'string', 'yes', 'Ticket / PNR (one family = one report vote)'], ['members[].segment', 'object', 'no', '{from, to} stop codes'], ['members[].party_size', 'int', 'no', ''], ['members[].seat_refs', 'array', 'no', 'Ops only'], ['members[].chart_status', 'enum', 'no', 'Train: waitlisted | rac | charted'], ['members[].gender', 'enum', 'no', 'M | F | O | U — only gates the women channel'], ['members[].locale', 'string', 'no', 'e.g. hi-IN'], ['members[].notify', 'object', 'no', '{push, sms, whatsapp}'], ['members[].profile', 'object', 'no', '{name, avatar}: the name they already chose in your app; skips the profile step']],
    ex: {
      bus: { req: { members: [{ external_user_id: 'abhi_u_88213', booking_ref: 'ABX7F3K21', segment: { from: 'GCBW', to: 'MJST' }, party_size: 2, seat_refs: ['L4', 'L5'], gender: 'F', notify: { push: true, sms: true } }] }, res: { added: [{ member_id: 'mem_3kd9x2ab', handle: 'Quiet Tiger', role: 'traveller' }], room_id: 'room_9f2k1abc', member_count: 15 } },
      train: { req: { members: [{ external_user_id: 'ctk_u_1201', booking_ref: '4521873390', segment: { from: 'KCG', to: 'YPR' }, seat_refs: ['B2-34'], chart_status: 'charted' }] }, res: { added: [{ member_id: 'mem_8tq1abcd', handle: 'Silver Otter', role: 'traveller' }] } },
      flight: { req: { members: [{ external_user_id: 'ixi_u_7781', booking_ref: 'X7K2QP', segment: { from: 'HYD', to: 'BLR' } }] }, res: { added: [{ member_id: 'mem_2fn7abcd', handle: 'Breezy Kingfisher', role: 'traveller' }], room_state: 'dormant' } },
    } },
  { id: 'byoc.message', group: 'Bring your own chat', method: 'POST', path: '/v1/rooms/{room_id}/members/{member_id}/messages', title: 'Mirror a traveller message', scope: 'members:write',
    description: 'You run your own chat UI but want the Console, moderation and the support desk. Send each traveller message here (idempotent per client_msg_id). Messages tagging @care, @support or @<App> Care become support tickets; agent replies come back on the action.updated webhook as `reply`, for you to show only to that traveller.',
    params: [['text', 'string', 'yes', '≤ 2000 chars; same safety filter as the hosted chat'], ['client_msg_id', 'string', 'yes', 'Your message id'], ['channel', 'enum', 'no', 'MAIN | WOMEN']],
    ex: { all: { req: { text: '@care the AC vent above 12L is leaking', client_msg_id: 'msg_8f2c1a', channel: 'MAIN' }, res: { message_id: '1b7c…', care_ticket: { id: 'act_k2m9x1ab', ref: 'IS-K2M9X1' } } } } },
  { id: 'byoc.sos', group: 'Bring your own chat', method: 'POST', path: '/v1/rooms/{room_id}/members/{member_id}/sos', title: 'Raise an SOS from your app', scope: 'members:write',
    description: 'Puts an Urgent SOS in the Ops inbox with the trip and best location attached. Never shown in the room.',
    params: [['reason', 'string', 'no', ''], ['coords', 'object', 'no', '{lat, lng}'], ['external_incident_id', 'string', 'no', 'Your incident id']],
    ex: { all: { req: { reason: 'Feeling unsafe', coords: { lat: 15.83, lng: 78.04 } }, res: { action_id: 'act_p3n8q2cd', ref: 'IS-P3N8Q2' } } } },
  { id: 'members.list', group: 'Members', method: 'GET', path: '/v1/rooms/{room_id}/members', title: 'List members', scope: 'rooms:read', description: 'Handles, roles, your external IDs.', params: [['role', 'query', 'no', 'traveller | crew']], ex: { all: { res: { data: [{ member_id: 'mem_3kd9x2ab', handle: 'Quiet Tiger', role: 'traveller', external_user_id: 'abhi_u_88213', muted: false, sharing_location: true }] } } } },
  { id: 'members.update', group: 'Members', method: 'PATCH', path: '/v1/rooms/{room_id}/members/{member_id}', title: 'Update a member', scope: 'members:write', description: 'Boarding point changed, party size, notification preferences, gender.', params: [['segment', 'object', 'no', ''], ['notify', 'object', 'no', ''], ['gender', 'enum', 'no', '']], ex: { all: { req: { segment: { from: 'KPHB', to: 'MJST' } }, res: { member_id: 'mem_3kd9x2ab', segment: { from: 'KPHB', to: 'MJST' } } } } },
  { id: 'members.remove', group: 'Members', method: 'DELETE', path: '/v1/rooms/{room_id}/members/{member_id}', title: 'Remove a member', scope: 'members:write', description: 'Call on cancellation. Access ends immediately.', params: [['reason', 'query', 'no', 'cancelled | no_show | moderation']], ex: { all: { res: { removed: true } } } },
  { id: 'members.move', group: 'Members', method: 'POST', path: '/v1/members:move', title: 'Move members between rooms', scope: 'members:write', description: 'Reschedules, bus swaps, flight changes and train charting (train-wide room → coach room). Members get a fresh handle in the new room.',
    params: [['from_room_id', 'string', 'yes', ''], ['to_room_id', 'string', 'yes', ''], ['member_ids', 'array', 'yes', ''], ['reason', 'enum', 'yes', 'reschedule | charting | vehicle_change | flight_change']], ex: { train: { req: { from_room_id: 'room_t7a11xyz', to_room_id: 'room_t7b20xyz', member_ids: ['mem_8tq1abcd'], reason: 'charting' }, res: { moved: 1 } }, bus: { req: { from_room_id: 'room_9f2k1abc', to_room_id: 'room_a81c2abc', member_ids: ['mem_3kd9x2ab'], reason: 'reschedule' }, res: { moved: 1 } }, flight: { req: { from_room_id: 'room_f3c90abc', to_room_id: 'room_f4d01abc', member_ids: ['mem_2fn7abcd'], reason: 'flight_change' }, res: { moved: 1 } } } },
  { id: 'members.token', group: 'Members', method: 'POST', path: '/v1/rooms/{room_id}/members/{member_id}/token', title: 'Get a member token (open the chat)', scope: 'members:write', description: 'Short-lived token for ONE member in ONE room. Open chat_url in a WebView (or pass the token to the React Native component). Mint a fresh one each time the traveller opens the trip.',
    params: [['ttl_sec', 'int', 'no', 'Default 3600, max 86400 (never past the purge time)']], ex: { all: { req: { ttl_sec: 3600 }, res: { token: 'eyJ…', expires_at: '2026-10-06T23:22:00+05:30', chat_url: 'https://rooms.example/?token=eyJ…', realtime_url: '/ws' } } } },

  { id: 'trip.events', group: 'Trip events', method: 'POST', path: '/v1/rooms/{room_id}/trip-events', title: 'Report a trip event', scope: 'rooms:write',
    description: 'The main way to keep a room accurate. Updates the room and, when auto_announce is true, posts a templated pinned alert (English + Hindi). Bus: delay, breakdown, vehicle_swap, boarding_point_change, stop_arrived, rest_stop_started, cancelled, diverted, resolved. Train: delay, platform_change, coach_position, stop_arrived, charting_done, cancelled, diverted, rescheduled. Flight: delay, gate_change, boarding_started, gate_closed, departed, landed, baggage_belt, cancelled, diverted.',
    params: [['type', 'enum', 'yes', 'See list'], ['minutes', 'int', 'delay / rest stop', 'Added to all ETAs (negative = recovered time)'], ['at_stop / station', 'string', 'no', 'Stop code'], ['platform / coach', 'string', 'train', ''], ['gate / terminal / belt', 'string', 'flight', ''], ['vehicle_no', 'string', 'bus swap', ''], ['reason', 'string', 'no', 'Shown in the alert'], ['auto_announce', 'bool', 'no', 'Default true'], ['channels', 'array', 'no', 'push, sms, whatsapp']],
    ex: { bus: { req: { type: 'delay', minutes: 25, at_stop: 'AMRP', reason: 'heavy traffic', channels: ['push', 'sms'] }, res: { event_id: 'evt_41aa', applied: { delay_min: 25, eta: { GCBW: '2026-10-06T22:40:00+05:30' } }, announcement_id: 'msg_…' } }, train: { req: { type: 'platform_change', station: 'MBNR', platform: '4' }, res: { event_id: 'evt_52bc', applied: { meta: { platform: '4' } } } }, flight: { req: { type: 'gate_change', gate: '14', terminal: 'T1', channels: ['push'] }, res: { event_id: 'evt_63cd', applied: { meta: { gate: '14', terminal: 'T1' } } } } } },
  { id: 'ann.create', group: 'Announcements', method: 'POST', path: '/v1/rooms/{room_id}/announcements', title: 'Post an Ops alert', scope: 'announcements:write', description: 'Free-text alert. Pinned by default. Ads pause for the configured window after any alert. Push/SMS go through YOUR notification stack: you receive notification.requested.',
    params: [['text', 'string', 'yes', 'Max 500'], ['severity', 'enum', 'yes', 'info | warning | critical'], ['pin', 'bool', 'no', 'Default true'], ['channels', 'object', 'no', '{push, sms, whatsapp}'], ['translations', 'object', 'no', '{"hi": "…"}'], ['author.ops_agent_id', 'string', 'no', 'For audit']],
    ex: { all: { req: { text: 'Bus is running 25 min late from Ameerpet.', severity: 'warning', channels: { push: true, sms: true }, translations: { hi: 'बस अमीरपेट से 25 मिनट देरी से चल रही है।' } }, res: { id: 'msg_…', delivered: { in_room: 14, push: 14, sms: 3 } } } } },
  { id: 'bc.create', group: 'Announcements', method: 'POST', path: '/v1/broadcasts', title: 'Broadcast to many rooms', scope: 'announcements:write', description: 'One alert to every room matching a selector. dry_run shows reach first. 10 per minute.',
    params: [['selector', 'object', 'yes', 'vertical + any of operator_id, route, train_no, flight_no, airport, date, states'], ['announcement', 'object', 'yes', 'Same shape as above'], ['dry_run', 'bool', 'no', '']],
    ex: { bus: { req: { selector: { vertical: 'bus', route: 'HYD-BLR', date: '2026-10-06' }, announcement: { text: 'NH44 closed near Kurnool. Buses are diverted; expect 60–90 min delay.', severity: 'warning' }, dry_run: true }, res: { matched_rooms: 12, reach: 184 } }, train: { req: { selector: { vertical: 'train', train_no: '12999' }, announcement: { text: 'Train is regulated near Dhone for track work.', severity: 'info' } }, res: { broadcast_id: 'bc_…', matched_rooms: 18, reach: 402 } }, flight: { req: { selector: { vertical: 'flight', airport: 'BLR' }, announcement: { text: 'Low visibility at Bengaluru. Expect delays.', severity: 'warning' } }, res: { broadcast_id: 'bc_…', matched_rooms: 9, reach: 611 } } } },

  { id: 'msg.list', group: 'Messages', method: 'GET', path: '/v1/rooms/{room_id}/messages', title: 'List messages', scope: 'rooms:read', description: 'Newest first, 50 per page. Includes hidden and private messages, flagged.', params: [['since', 'query', 'no', 'ISO time'], ['cursor', 'query', 'no', ''], ['channel', 'query', 'no', 'MAIN | WOMEN']], ex: { all: { res: { data: [{ id: 'msg_1', contentType: 'TEXT', senderHandle: 'Amber Owl', payload: { text: 'Has it crossed Kukatpally?' }, hidden: false }], next_cursor: 'c_2' } } } },
  { id: 'msg.post', group: 'Messages', method: 'POST', path: '/v1/rooms/{room_id}/messages', title: 'Post as bot or system', scope: 'announcements:write', description: 'For bots (e.g. your LLM behind Tara) and system notices. Travellers post through the chat screen.', params: [['as', 'enum', 'yes', 'bot | system'], ['bot_id', 'string', 'if bot', ''], ['text', 'string', 'yes', ''], ['channel', 'enum', 'no', 'MAIN | WOMEN | ALL']], ex: { all: { req: { as: 'bot', bot_id: 'bot_tara01', text: 'The bus is near KPHB, about 18 min from Gachibowli.' }, res: { id: 'msg_92' } } } },
  { id: 'msg.delete', group: 'Messages', method: 'DELETE', path: '/v1/rooms/{room_id}/messages/{message_id}', title: 'Remove a message', scope: 'moderation:write', description: 'Removes for everyone. Logged.', params: [['reason', 'query', 'no', 'abuse | spam | personal_info | other']], ex: { all: { res: { removed: true } } } },

  { id: 'loc.push', group: 'Location', method: 'POST', path: '/v1/rooms/{room_id}/location/sources', title: 'Push an official location feed', scope: 'location:write', description: 'Device GPS (VTS), train running status or flight status. A fresh official feed always beats crowd location. Delay and gate facts in the feed are applied as trip events (announced when they change by 10+ min).',
    params: [['source', 'enum', 'yes', 'vts | running_status | flight_status'], ['points[]', 'array', 'vts', 'lat, lng, ts, speed_kmph'], ['last_station / next_station / delay_min', 'mixed', 'train', ''], ['status / gate / terminal / est_departure / est_arrival', 'mixed', 'flight', '']],
    ex: { bus: { req: { source: 'vts', device_id: 'VTS-88', points: [{ lat: 17.4482, lng: 78.3912, ts: '2026-10-06T22:21:30+05:30', speed_kmph: 34 }] }, res: { accepted: 1, triggered: null } }, train: { req: { source: 'running_status', last_station: 'MBNR', delay_min: 12, next_station: 'KRNT' }, res: { accepted: 1 } }, flight: { req: { source: 'flight_status', status: 'delayed', gate: '12', est_departure: '2026-10-06T23:20:00+05:30' }, res: { accepted: 1, triggered: 'activation.on_delay' } } } },
  { id: 'loc.get', group: 'Location', method: 'GET', path: '/v1/rooms/{room_id}/location', title: 'Get the best current position', scope: 'rooms:read', description: 'Fused from the official feed, on-board travellers and the timetable, with a confidence level. Use it on your Track page too.', params: [],
    ex: { bus: { res: { near: 'between KPHB and Gachibowli', progress: 0.12, source: '3 travellers on board', confidence: 'high', contributors: 3, next_stop: { code: 'GCBW', name: 'Gachibowli', eta: '2026-10-06T22:40:00+05:30' }, stale_after_sec: 180 } }, train: { res: { near: 'between Kacheguda and Mahbubnagar', source: 'Running status', confidence: 'high' } }, flight: { res: { near: 'at Hyderabad', source: 'Flight status', confidence: 'high', meta: { gate: '12' } } } } },

  { id: 'poll.create', group: 'Polls, surveys & games', method: 'POST', path: '/v1/rooms/{room_id}/polls', title: 'Post a poll', scope: 'announcements:write', description: '2–4 options. Results arrive as poll.completed when it closes.', params: [['question', 'string', 'yes', ''], ['options', 'array', 'yes', '2–4'], ['closes_in_min', 'int', 'no', 'Default 30'], ['campaign_id', 'string', 'no', 'Marks it sponsored']], ex: { all: { req: { question: 'Is the AC temperature okay?', options: ['Too cold', 'Just right', 'Too warm'], closes_in_min: 20 }, res: { id: 'msg_31' } } } },
  { id: 'survey.create', group: 'Polls, surveys & games', method: 'POST', path: '/v1/surveys', title: 'Create a survey template', scope: 'campaigns:write', description: 'Up to 4 questions: rating, single choice or short text.', params: [['name', 'string', 'yes', ''], ['questions[]', 'array', 'yes', 'type: rating | choice | text']], ex: { all: { req: { name: 'Boarding experience', questions: [{ type: 'rating', q: 'How easy was it to find your boarding point?' }, { type: 'choice', q: 'How did you find the bus?', options: ['Live tracking', 'Called the driver', 'Asked in the trip room', 'Other'] }] }, res: { id: 'srv_8abc' } } } },
  { id: 'survey.attach', group: 'Polls, surveys & games', method: 'POST', path: '/v1/rooms/{room_id}/surveys', title: 'Send a survey to a room', scope: 'campaigns:write', description: 'Now, or when the room goes read-only.', params: [['survey_id', 'string', 'yes', ''], ['trigger', 'enum', 'no', 'now | on_drop | on_read_only']], ex: { all: { req: { survey_id: 'srv_8abc', trigger: 'now' }, res: { sent: true } } } },
  { id: 'games.list', group: 'Polls, surveys & games', method: 'GET', path: '/v1/games', title: 'List games', scope: 'rooms:read', description: 'Low-bandwidth room games.', params: [], ex: { all: { res: { data: [{ id: 'QUIZ', name: 'Bus Quiz (trip trivia)', players: '1–50' }, { id: 'EMOJI', name: 'Guess the Movie', players: '1–50' }, { id: 'TTT', name: 'Tic-tac-toe', players: '2 (others watch)' }] } } } },
  { id: 'games.start', group: 'Polls, surveys & games', method: 'POST', path: '/v1/rooms/{room_id}/games', title: 'Start a room game', scope: 'announcements:write', description: 'Hosted games, optionally sponsored.', params: [['game', 'enum', 'yes', 'QUIZ | EMOJI'], ['campaign_id', 'string', 'no', 'Sponsor label']], ex: { all: { req: { game: 'QUIZ', campaign_id: 'cmp_5abc' }, res: { game_session: 'msg_12' } } } },
  { id: 'voucher.issue', group: 'Polls, surveys & games', method: 'POST', path: '/v1/rooms/{room_id}/vouchers', title: 'Drop a delay voucher', scope: 'announcements:write', description: 'A claimable voucher card. You credit the wallet when you receive voucher.claimed.', params: [['amount', 'int', 'yes', 'INR'], ['note', 'string', 'no', '']], ex: { all: { req: { amount: 100, note: 'For the 2-hour delay' }, res: { id: 'msg_…' } } } },

  { id: 'camp.create', group: 'Campaigns', method: 'POST', path: '/v1/campaigns', title: 'Create a campaign', scope: 'campaigns:write', description: 'Usually from the Marketing console. Tenant ad rules always apply on top (frequency, quiet hours, no ads after alerts or during breakdowns).',
    params: [['name / advertiser', 'string', 'yes', ''], ['format', 'enum', 'yes', 'card | sponsored_poll | sponsored_game | stop_offer | survey'], ['creative', 'object', 'cards', 'title, body (≤70), cta, tile'], ['poll / survey', 'object', 'format', ''], ['targeting', 'object', 'yes', 'tenants, verticals, routes, stops, stages'], ['schedule', 'object', 'no', 'start, end'], ['cap.impressions', 'int', 'no', '']],
    ex: { all: { req: { name: 'Kurnool dinner offer', advertiser: 'Dhaba Express', format: 'stop_offer', creative: { title: 'Dhaba Express, Kurnool', body: 'Free chai with any thali tonight', cta: 'Show coupon' }, targeting: { verticals: ['bus'], routes: ['HYD-BLR'], stops: ['KRNL'], stages: ['onboard'] }, cap: { impressions: 50000 } }, res: { id: 'cmp_1abc', status: 'live' } } } },
  { id: 'camp.stats', group: 'Campaigns', method: 'GET', path: '/v1/campaigns/{campaign_id}/stats', title: 'Campaign results', scope: 'campaigns:write', description: 'Impressions, clicks, responses, and hold-backs by rule.', params: [], ex: { all: { res: { stats: { impressions: 1840, clicks: 212, responses: 0, ctr: 11.52 }, delivered_rooms: 41, held_back: { 'quiet hours': 410, 'Ops alert in last 15 min': 52, '1 ad per 45 min': 118 } } } } },

  { id: 'act.list', group: 'Safety & Ops', method: 'GET', path: '/v1/actions', title: 'List Ops actions', scope: 'moderation:write', description: 'SOS, group issues, wait requests, lost items and reports, across your rooms.', params: [['type', 'query', 'no', 'sos | issue | wait_request | lost_found | report'], ['status', 'query', 'no', 'open | acknowledged | resolved']], ex: { all: { res: { data: [{ id: 'act_1abc', type: 'sos', severity: 'critical', room_id: 'room_9f2k1abc', member_id: 'mem_3kd9x2ab', title: 'I feel unsafe', status: 'open' }] } } } },
  { id: 'act.update', group: 'Safety & Ops', method: 'PATCH', path: '/v1/actions/{action_id}', title: 'Update an action', scope: 'moderation:write', description: 'Acknowledge, reply privately (only that traveller sees it), resolve.', params: [['status', 'enum', 'no', ''], ['private_reply', 'string', 'no', '']], ex: { all: { req: { status: 'acknowledged', private_reply: 'We’re calling you now on a masked line.' }, res: { id: 'act_1abc', status: 'acknowledged' } } } },
  { id: 'mod.act', group: 'Safety & Ops', method: 'POST', path: '/v1/rooms/{room_id}/moderation', title: 'Moderate a room', scope: 'moderation:write', description: 'Mute or remove a member, switch to Ops-only, or turn on slow mode (optionally for N minutes).', params: [['action', 'enum', 'yes', 'mute_member | unmute_member | remove_member | ops_only | slow_mode'], ['member_id', 'string', 'member actions', ''], ['enabled', 'bool', 'room actions', ''], ['duration_min', 'int', 'no', '']], ex: { all: { req: { action: 'ops_only', enabled: true, duration_min: 30 }, res: { applied: true, ops_only: true } } } },
  { id: 'mod.reveal', group: 'Safety & Ops', method: 'POST', path: '/v1/members/{member_id}/reveal', title: 'Reveal the booking behind a handle', scope: 'moderation:write', description: 'With a reason. Every reveal is logged and reviewed weekly.', params: [['reason', 'enum', 'yes', 'sos | harassment | lost_found | legal'], ['ops_agent_id', 'string', 'yes', '']], ex: { all: { req: { reason: 'sos', ops_agent_id: 'ops.ravi' }, res: { booking_ref: 'ABX7F3K21', external_user_id: 'abhi_u_88213', audit_id: 'aud_77' } } } },

  { id: 'bots.reg', group: 'Bots, config & webhooks', method: 'POST', path: '/v1/bots', title: 'Register a bot', scope: 'config:write', description: 'Plug an LLM in behind Tara or add your own bot. We POST bot.message_received to webhook_url; reply with “Post as bot”.', params: [['name', 'string', 'yes', ''], ['label', 'string', 'yes', 'Badge, e.g. AI'], ['webhook_url', 'url', 'no', ''], ['triggers', 'array', 'yes', 'mention | question | location_question | catch_up']], ex: { all: { req: { name: 'Tara', label: 'AI', webhook_url: 'https://tara.example/rooms', triggers: ['mention', 'location_question', 'catch_up'] }, res: { id: 'bot_tara01' } } } },
  { id: 'cfg', group: 'Bots, config & webhooks', method: 'PATCH', path: '/v1/tenants/{tenant}/config', title: 'Update tenant defaults', scope: 'config:write', description: 'Features, identity mode (handle | profile), timings, quiet hours, ad rules, thresholds. Same settings as Tenants & config.', params: [['features', 'object', 'no', ''], ['identity.mode', 'enum', 'no', 'handle | profile'], ['timing', 'object', 'no', 'open_before_min, readonly_after_min, purge_days'], ['quiet', 'object', 'no', 'from, to'], ['ads', 'object', 'no', 'gap_min, max_per_trip, block_after_alert_min'], ['social_min / report_hide_at / issue_escalate_at', 'int', 'no', '']], ex: { all: { req: { features: { games: true, ads: true }, timing: { open_before_min: 180 }, ads: { gap_min: 45, max_per_trip: 4 } }, res: { tenant: 'abhibus', version: 12 } } } },
  { id: 'wh.reg', group: 'Bots, config & webhooks', method: 'POST', path: '/v1/webhooks', title: 'Subscribe to events', scope: 'webhooks:write', description: 'Signed with HMAC-SHA256 in X-TripRooms-Signature (t=…,v1=…). Retries with backoff for 24 h. Use "*" or "sos.*" patterns.', params: [['url', 'url', 'yes', ''], ['events', 'array', 'yes', 'See Webhooks']], ex: { all: { req: { url: 'https://api.abhibus.example/hooks/rooms', events: ['sos.raised', 'issue.escalated', 'wait_request.raised', 'room.state_changed', 'notification.requested'] }, res: { id: 'wh_4abc', secret: 'whsec_…' } } } },

  { id: 'rt', group: 'Chat screen', method: 'WSS', path: '/ws?token={member_token}', title: 'Hosted chat screen & realtime', description: 'You don’t call this. Open chat_url from the member token in a WebView, or render <TripRoom token theme /> in React Native. The screen handles realtime, offline queueing, location consent, games and every safety rule.', params: [['chat_url', 'url', '', 'From members/{id}/token'], ['theme', 'query', 'no', 'Tenant theme is applied automatically']], ex: { all: { req: { open: 'https://rooms.example/?token=eyJ…' }, res: { events: ['message:new', 'room:update', 'location:estimate', 'pinned:update', 'private:new'] } } } },
];

export const WEBHOOK_EVENTS: [string, string][] = [
  ['room.created', 'Room created by API'], ['room.opened', 'Room opened for travellers'], ['room.state_changed', 'open, onboard, read_only, closed'], ['room.updated', ''], ['room.purged', 'Traveller content deleted'],
  ['member.joined / member.left / member.moved', ''], ['member.muted / member.revealed', 'Moderation + identity reveal (audited)'],
  ['message.reported', 'A message or person was reported'], ['sos.raised', 'Critical. Member, reason, best location'], ['issue.reported / issue.escalated', 'Group issue crossed the threshold'],
  ['wait_request.raised', 'Traveller running late to boarding'], ['lost_found.created', ''], ['action.updated', 'Acknowledged / replied / resolved'],
  ['announcement.created', 'Ops alert posted'], ['notification.requested', 'Send push / SMS / WhatsApp through your stack'], ['broadcast.sent', ''],
  ['trip_event.<type>', 'Every trip event applied'], ['location.updated', 'Stop reached / confidence changed'],
  ['poll.completed', 'Final results'], ['survey.response', ''], ['voucher.issued / voucher.claimed', 'Credit the wallet on claim'], ['trip.rated', 'Stars'],
  ['ad.delivered / ad.clicked / survey.delivered', 'For billing'], ['game.started', ''], ['bot.replied', 'Tara answered'], ['care.mentioned', 'Traveller tagged your customer care'], ['tenant.config_updated', ''],
];
