#!/usr/bin/env bash
# Copies the shared realtime contract + moderation filter into both apps.
# Run after editing anything in /shared.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
for target in "$ROOT/server/src/shared" "$ROOT/mobile/src/shared"; do
  mkdir -p "$target"
  for f in protocol.ts moderation.ts; do
    { echo "// AUTO-GENERATED by scripts/sync-shared.sh — edit /shared/$f instead."; cat "$ROOT/shared/$f"; } > "$target/$f"
  done
done
echo "✔ shared contract synced to server/ and mobile/"
